name: ml_image_store_server
description: Ml Image Store Server
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  archive: ^3.4.10
  dart_frog: ^1.0.0
  dart_frog_auth: ^1.1.0

  ml_image_store:
    path: ../ml_image_store
  image: ^4.1.7
  postgres: ^3.1.2
  shelf_cors_headers: ^0.1.5
  uuid:

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
